### ISSUE TITLE
Encountered minor build issue

### ISSUE THREAD

**Issue by cmcl** [andrejbauer/coop#3]
Hi Andrej & Danel,

Firstly, congrats on your ESOP submission being accepted. Exciting work!

I encountered a minor build issue when trying to make the coop executable. Perhaps it is a platform issue (I am running Linux Mint 19.2 Tina), but the library "menhirlib" specified in the src/dune file is case sensitive on my system; the correct library name is: "menhirLib".

Looking forward to playing around with coop!

Best,
Craig

**Comment by andrejbauer** [comment]
Could you submit a PR that works on Linux and if it also works on MacOS that's that. (The other way around is less pleasant: me trying to guess on MacOS what change to make so that it'll work on Linux.)

**Comment by andrejbauer** [comment]
This is closed by #6.
